export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const TEACHERREG_LOADING = 'TEACHERREG_LOADING';
export const TEACHERREG_FAILED = 'TEACHERREG_FAILED';
export const ADD_TEACHERREG = 'ADD_TEACHERREG';

export const STUDENTREG_LOADING = 'STUDENTREG_LOADING';
export const STUDENTREG_FAILED = 'STUDENTREG_FAILED';
export const ADD_STUDENTREG = 'ADD_STUDENTREG';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const ADD_PROFILE = 'ADD_PROFILE';
export const EMPTY_PROFILE = 'EMPTY_PROFILE';

export const COURSEINFO_LOADING = 'COURSEINFO_LOADING';
export const COURSEINFO_FAILED = 'COURSEINFO_FAILED';
export const ADD_COURSEINFO = 'ADD_COURSEINFO';